In [1]:
# Que.4 -
# Prepare a model for glass classification using KNN and SVM.
# Data Description:
# RI : refractive index
# Na: Sodium (unit measurement: weight percent in corresponding oxide, as are attributes 4-10)
# Mg: Magnesium
# AI: Aluminum
# Si: Silicon
# K:Potassium
# Ca: Calcium
# Ba: Barium
# Fe: Iron
# Type: Type of glass: (class attribute)
# 1 -- building_windows_float_processed
#  2 --building_windows_non_float_processed
#  3 --vehicle_windows_float_processed
#  4 --vehicle_windows_non_float_processed (none in this database)
#  5 --containers
#  6 --tableware
#  7 --headlamps

# Dataset : Glass.csv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('glass.csv')
df.head()

        RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [2]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
encoder.fit(df['Type'])
df['Type'] = encoder.transform(df['Type'])
df['Type']

0      0
1      0
2      0
3      0
4      0
      ..
209    5
210    5
211    5
212    5
213    5
Name: Type, Length: 214, dtype: int64

In [3]:
df.corr()

,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe,Type
RI,1.000000,-0.191885,-0.122274,-0.407326,-0.542052,-0.289833,0.810403,-0.000386,0.143010,-0.168739
Na,-0.191885,1.000000,-0.273732,0.156794,-0.069809,-0.266087,-0.275442,0.326603,-0.241346,0.506424
Mg,-0.122274,-0.273732,1.000000,-0.481799,-0.165927,0.005396,-0.443750,-0.492262,0.083060,-0.728160
Al,-0.407326,0.156794,-0.481799,1.000000,-0.005524,0.325958,-0.259592,0.479404,-0.074402,0.591198
Si,-0.542052,-0.069809,-0.165927,-0.005524,1.000000,-0.193331,-0.208732,-0.102151,-0.094201,0.149691
K,-0.289833,-0.266087,0.005396,0.325958,-0.193331,1.000000,-0.317836,-0.042618,-0.007719,-0.025835
Ca,0.810403,-0.275442,-0.443750,-0.259592,-0.208732,-0.317836,1.000000,-0.112841,0.124968,-0.008998
Ba,-0.000386,0.326603,-0.492262,0.479404,-0.102151,-0.042618,-0.112841,1.000000,-0.058692,0.577676
Fe,0.143010,-0.241346,0.083060,-0.074402,-0.094201,-0.007719,0.124968,-0.058692,1.000000,-0.183207
Type,-0.168739,0.506424,-0.728160,0.591198,0.149691,-0.025835,-0.008998,0.577676,-0.183207,1.000000

In [4]:
X = df.drop(['RI','Si','K','Ca','Fe','Type'],axis = 1)
Y = df[['Type']]

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,train_size = 0.7,random_state = 12345)

In [6]:
def build_knn_model():
    from sklearn.neighbors import KNeighborsClassifier
    model = KNeighborsClassifier()
    model.fit(x_train,y_train)
    return model

In [7]:
def build_svm_model():
    from sklearn.svm import SVC
    model = SVC(C = 2.0)
    model.fit(x_train,y_train)
    return model

In [8]:
def evaluate_model(model):
    y_true = y_test
    y_pred = model.predict(x_test)
    from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

    accuracy = f"{accuracy_score(y_true, y_pred):.2f}"
    precision = f"{precision_score(y_true, y_pred,average = 'micro'):.2f}"
    recall = f"{recall_score(y_true, y_pred,average = 'micro'):.2f}"
    f1 = f"{f1_score(y_true, y_pred,average = 'micro'):.2f}"

    return accuracy, precision, recall, f1

In [9]:
evaluation_report = []

model_knn = build_knn_model()
evaluation_report.append({"model": "KNN", "metrics": evaluate_model(model_knn)})

model_svm = build_svm_model()
evaluation_report.append({"model": "support vector machine", "metrics": evaluate_model(model_svm)})

/home/user/.local/lib/python3.10/site-packages/sklearn/neighbors/_classification.py:233: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/home/user/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [10]:
print(f"{'Algorithm':<20} => 'Accuracy', 'precision', 'recall', 'f1'")
print()
for info in evaluation_report:
    print(f"{info['model']:<20} => {info['metrics']}")

Algorithm            => 'Accuracy', 'precision', 'recall', 'f1'

KNN                  => ('0.57', '0.57', '0.57', '0.57')
support vector machine => ('0.45', '0.45', '0.45', '0.45')